// Flat ESLint config (ESLint 9 + typescript-eslint 8).
// Pragmatic ruleset for a large existing Next.js/TypeScript codebase:
// it flags real correctness smells (unreachable code, bad regex, control-flow
// bugs) without drowning the repo in stylistic noise. Type-aware linting is
// intentionally left off so `pnpm lint` stays fast and self-contained.
import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import globals from 'globals'
import nextPlugin from '@next/eslint-plugin-next'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import reactHooks from 'eslint-plugin-react-hooks'

export default tseslint.config(
  {
    // Generated, vendored, or non-JS/TS areas — never linted.
    ignores: [
      '.next/**',
      'node_modules/**',
      // Generated by `test:coverage`. CI lints before it tests, so it has
      // never seen this directory; a developer running the gates in the
      // other order got warnings about instrumentation they did not write.
      'coverage/**',
      'public/**',
      'desktop/**',
      'desktop-office/**',
      'contracts/**/artifacts/**',
      'contracts/**/cache/**',
      'contracts/**/out/**',
      'sdk/**/dist/**',
      '**/*.d.ts',
      'pnpm-lock.yaml',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx,mts,cts,js,mjs,cjs}'],
    plugins: {
      '@next/next': nextPlugin,
      'jsx-a11y': jsxA11y,
      'react-hooks': reactHooks,
    },
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.browser,
      },
    },
    rules: {
      // Next.js best practices (recommended + core-web-vitals baseline).
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      // React hooks correctness — rules-of-hooks is a real bug, deps is advisory.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      // <img> and un-captioned media are gradual improvements, not build blockers.
      '@next/next/no-img-element': 'warn',
      'jsx-a11y/media-has-caption': 'warn',

      // Real bugs — keep as errors.
      'no-constant-binary-expression': 'error',
      'no-unreachable': 'error',
      'no-fallthrough': 'error',
      'no-self-compare': 'error',
      'no-unsafe-negation': 'error',

      // Pragmatic relaxations for an established codebase. These are style /
      // gradual-typing choices, not correctness issues, so they must not gate CI.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      'no-empty': ['warn', { allowEmptyCatch: true }],
    },
  },
)
